### ISSUE TITLE
auto calculate OperationType

### ISSUE THREAD

**Issue by Lomet** [The-Poolz/DispenserProvider.DataBase#28]
https://github.com/The-Poolz/DispenserProvider.DataBase/blob/57ecfbe8b524939983d247d7f8afeb79c3e61adf/src/DispenserProvider.DataBase/Models/LogDTO.cs#L15

this can be linked only for one place.

**Comment by ArdenHide** [comment]
EFCore doesn't support auto-calculated columns based on navigation property
